[project]
name = "bot-hafalan"
version = "0.1.0"
description = "Bot Telegram untuk Hafalan Santri"
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"

dependencies = [
    "python-telegram-bot==20.8",
    "Flask>=2.2",
    "gunicorn>=20.1",
    "sqlite3"
]
